env:
  browser: true
  es2021: true
extends: []
  # - eslint:recommended
  # - plugin:@typescript-eslint/recommended
  # - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/no-floating-promises": error,
    notabs: off,
    camelcase: off,
    indent: off,
    quotes: off,
    operator-linebreak: off,
    padded-blocks: off,
    func-names: off,
    no-trailing-spaces: off,
    comma-dangle: off,
    prefer-template: off,
  }
