version: "3.3"

services:
  jest:
    build: .
    command: yarn jest

  sut:
    build: .
    command: yarn test
    environment:
      - AMQP_HOST=amqp
      - AMQP_USER='user'
      - AMQP_PASSWORD='my_password'
      - AMQP_EXCHANGE=test
      - AMQP_VHOST='test'
    ports:
      - '15672:15672'
    depends_on: 
      - amqp
  amqp:
    image: 'bitnami/rabbitmq:latest'
    environment:
      - RABBITMQ_PASSWORD=my_password
      - RABBITMQ_USERNAME=user
  redis:
    image: 'bitnami/redis:latest'
