version: "3.3"

services:
  amqp:
    image: rabbitmq
    environment:
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_USERNAME=guest
    # logging:
    #   driver: "none"
    ports:
      - '5672:5672'

  redis:
    image: redis
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    # logging:
    #   driver: "none"

  order-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./services/order-tracker/binance-order-tracker.ts --live=false
    restart: never
    environment:
      - AMQP_HOST=amqp
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - AMQP_EXCHANGE=test
      - AMQP_PROTOCOL=amqp
      - AMQP_VHOST=/
      - REDIS_HOST=redis
    depends_on: 
      - redis
      - amqp

  # price-monitor:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ./services/price-monitor.ts --live=false
  #   restart: on-failure
  #   environment:
  #     - AMQP_HOST=amqp
  #     - AMQP_USER=guest
  #     - AMQP_PASSWORD=guest
  #     - AMQP_EXCHANGE=test
  #     - AMQP_VHOST=/
  #     - AMQP_PROTOCOL=amqp
  #     - REDIS_HOST=redis
  #   depends_on: 
  #     - redis
  #     - amqp

  # redis-monitor:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ./services/redis-monitor.ts
  #   restart: on-failure
  #   environment:
  #     - AMQP_HOST=amqp
  #     - AMQP_USER=guest
  #     - AMQP_PASSWORD=guest
  #     - AMQP_EXCHANGE=test
  #     - AMQP_VHOST=/
  #     - AMQP_PROTOCOL=amqp
  #     - REDIS_HOST=redis
  #   depends_on: 
  #     - redis

