{
 "title": "Backtest Overview",
 "time": { "from": "2022-04-14T20:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "backtest_run_id",
    "label": "Backtest Run ID",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: v.bucket,\n    tag: \"backtest_run_id\",\n    predicate: (r) => true,\n    start: -1d\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Profit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"portfolio\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"$backtest_run_id\")  \n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true )\n  \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Assets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"portfolio\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"${backtest_run_id}\")  \n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true )\n  \n  \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Loan",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"portfolio\")\n  |> filter(fn: (r) => r._field == \"loan\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"$backtest_run_id\")  \n  \n\n\n  \n  \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Portfolio Value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"portfolio\")\n  |> filter(fn: (r) => r._field == \"total\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"${backtest_run_id}\")  \n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false )\n  \n\n\n \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Portfolio Cash vs Investments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"portfolio\")\n  |> filter(fn: (r) => r._field == \"investments\" or r._field == \"cash\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"$backtest_run_id\")  \n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false )\n\n\n \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Count of Open Positions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"portfolio\")\n  |> filter(fn: (r) => r._field == \"open_positions_count\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"${backtest_run_id}\")  \n \n\n\n\n \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Investments Value",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"e70-backtests-1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"position\")\n  |> filter(fn: (r) => r._field == \"quote_value\")\n  |> filter(fn: (r) => r[\"backtest_run_id\"] == \"${backtest_run_id}\")  \n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: true )\n  \n\n\n \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}