apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-futures-portfolio-tracker
  labels:
{{ include "binance-futures.labels" . | indent 4 }}
    binance-tool/service: "binance-futures-portfolio-tracker"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "binance-futures.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "binance-futures.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "binance-futures-portfolio-tracker"
      annotations:
        ad.datadoghq.com/tags: '{"service": "binance-futures-portfolio-tracker"}'
        ad.datadoghq.com/binance-futures-portfolio-tracker.logs: >-
          [{
            "source": "nodejs",
            "service": "binance-futures-portfolio-tracker"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      containers:
        - name: binance-futures-portfolio-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/binance/futures/portfolio-tracker/binance-futures-portfolio-tracker"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
            - name: SENTRY_DSN
              value: "https://79705006c9a14dfeb9c065f5b518c2cf@o369902.ingest.sentry.io/6554868"
{{- include "binance-futures.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
