apiVersion: v1
kind: Service
metadata:
  name: binance-futures-trade-abstraction
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: binance-futures-trade-abstraction
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-futures-trade-abstraction
  labels:
    binance-tool/service: "binance-futures-trade-abstraction"
    tags.datadoghq.com/service: "binance-futures-trade-abstraction"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: binance-futures-trade-abstraction
  template:
    metadata:
      labels:
        binance-tool/service: "binance-futures-trade-abstraction"
        app: binance-futures-trade-abstraction
        tags.datadoghq.com/service: "binance-futures-trade-abstraction"
      annotations:
        ad.datadoghq.com/tags: '{"service": "binance-futures-trade-abstraction"}'
        ad.datadoghq.com/binance-futures-trade-abstraction.logs: >-
          [{
            "source": "nodejs",
            "service": "binance-futures-trade-abstraction"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: binance-futures-trade-abstraction
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/binance/futures/trade-abstraction/tas"]
          ports:
          - name: http
            containerPort: 3000
            protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /health
              port: http
          startupProbe: # First time this goes healthy livenessProbe is activated
            httpGet:
              path: /health
              port: http
            failureThreshold: 30 # 30 * 10 = 5 minutes
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            - name: SENTRY_DSN
              value: "https://79ec51cc53f64c6fa2227c5108f65cfd@o369902.ingest.sentry.io/6402822" # binance-futures-tas
{{- include "binance-futures.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
