apiVersion: v1
kind: Service
metadata:
  name: futures-trade-abstraction
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: futures-trade-abstraction
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: futures-trade-abstraction
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "futures-trade-abstraction"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: futures-trade-abstraction
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "futures-trade-abstraction"
        app: futures-trade-abstraction
      annotations:
        ad.datadoghq.com/tags: '{"service": "futures-trade-abstraction"}'
        ad.datadoghq.com/futures-trade-abstraction.logs: >-
          [{
            "source": "nodejs",
            "service": "futures-trade-abstraction"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: futures-trade-abstraction
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./services/futures-trade-abstraction/tas.ts"]
          ports:
          - name: http
            containerPort: 3000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          env:
            - name: SENTRY_DSN
              value: "https://5a68a728462448d08b613731e9e51d0d@o369902.ingest.sentry.io/6151233"
{{- include "binance-futures.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
