apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-spot-binance-position-tracker
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "amqp-spot-binance-position-tracker"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "amqp-spot-binance-position-tracker"
        tags.datadoghq.com/service: "amqp-spot-binance-position-tracker"
      annotations:
        ad.datadoghq.com/tags: '{"service": "amqp-spot-binance-position-tracker"}'
        ad.datadoghq.com/amqp-spot-binance-position-tracker.logs: >-
          [{
            "source": "nodejs",
            "service": "amqp-spot-binance-position-tracker"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      containers:
        - name: amqp-spot-binance-position-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/amqp/binance-order-data/position-tracker/binance-spot-position-tracker"]
          resources:
            requests:
              memory: 100M
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /health
              port: http
          startupProbe: # First time this goes healthy livenessProbe is activated
            httpGet:
              path: /health
              port: http
            failureThreshold: 30 # 30 * 10 = 5 minutes
            periodSeconds: 10
          env:
            - name: SENTRY_DSN
              value: "https://f999d04298a34caa82c13839699a266f@o369902.ingest.sentry.io/5735251"
{{- include "telegram.vars" . | nindent 12 }}
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
