apiVersion: apps/v1
kind: Deployment
metadata:
  name: binance-position-tracker
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "binance-position-tracker"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "binance-position-tracker"
        tags.datadoghq.com/service: "binance-position-tracker"
      annotations:
        ad.datadoghq.com/tags: '{"service": "binance-position-tracker"}'
        ad.datadoghq.com/binance-position-tracker.logs: >-
          [{
            "source": "nodejs",
            "service": "binance-position-tracker"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      containers:
        - name: binance-position-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./services/position-tracker/binance-spot-position-tracker.ts", "--live"]
          # ports:
          # - name: http
          #   containerPort: 80
          #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
            - name: SENTRY_DSN
              value: "https://f999d04298a34caa82c13839699a266f@o369902.ingest.sentry.io/5735251"
{{- include "telegram.vars" . | nindent 12 }}
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
