apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-tracker
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "order-tracker"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "order-tracker"
      annotations:
        ad.datadoghq.com/tags: '{"service": "order-tracker"}'
  
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointerdir
      containers:
        - name: order-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./services/order-tracker.ts"]
          volumeMounts:
            - name: pointerdir
              mountPath: /opt/datadog-agent/run
          # ports:
          # - name: http
          #   containerPort: 8081
          #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-monitor
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "price-monitor"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "price-monitor"
      annotations:
        ad.datadoghq.com/tags: '{"service": "price-monitor"}'
  
    spec:
      volumes:
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointerdir
      containers:
        - name: price-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./services/price-monitor.ts"]
          volumeMounts:
            - name: pointerdir
              mountPath: /opt/datadog-agent/run
          # ports:
          # - name: http
          #   containerPort: 8081
          #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-monitor
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "redis-monitor"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "redis-monitor"
      annotations:
        ad.datadoghq.com/tags: '{"service": "redis-monitor"}'
    spec:
      volumes:
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointerdir
      containers:
        - name: redis-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./services/redis-monitor.ts"]
          volumeMounts:
            - name: pointerdir
              mountPath: /opt/datadog-agent/run
          env:
{{- include "datadog.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}

