apiVersion: v1
kind: Service
metadata:
  name: edge70-60d-signals
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: edge70-60d-signals
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge70-60d-signals
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "edge70-60d-signals"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: edge70-60d-signals
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edge70-60d-signals
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "edge70-60d-signals"
        tags.datadoghq.com/service: "edge70-60d-signals"
      annotations:
        ad.datadoghq.com/tags: '{"service": "edge70-60d-signals"}'
        ad.datadoghq.com/edge70-60d-signals.logs: >-
          [{
            "source": "nodejs",
            "service": "edge70-60d-signals"
          }]   
    spec:
      priorityClassName: binance-edge-signals
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      containers:
        - name: edge70-60d-signals
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/edge70-signals/edge70-service", "--live"]
          resources:
            requests:
              memory: 250M
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /health
              port: http
          startupProbe: # First time this goes healthy livenessProbe is activated
            httpGet:
              path: /ready
              port: http
            failureThreshold: 60 # 60 * 10 = 10 minutes (seen 6-7 minutes on deploy)
            periodSeconds: 10
          env:
            - name: SENTRY_DSN
              value: "https://061417a8381f424d862e470111d60ca4@o369902.ingest.sentry.io/6621800"
            - name: EDGE_CONFIGURATION_NAME
              value: edge70-60
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
---
