apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge60
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "edge60"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "edge60"
      annotations:
        ad.datadoghq.com/tags: '{"service": "edge60"}'
        ad.datadoghq.com/edge60.logs: >-
          [{
            "source": "nodejs",
            "service": "edge60"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      containers:
        - name: edge60
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/edge60/edge60-service", "--live"]
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          env:
            - name: SENTRY_DSN
              value: "https://ec7e90a79b4e48ac8727fc5de7bfc454@o369902.ingest.sentry.io/6112658"
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
---
