apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge61
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "edge61"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "edge61"
      annotations:
        ad.datadoghq.com/tags: '{"service": "edge61"}'
        ad.datadoghq.com/edge61.logs: >-
          [{
            "source": "nodejs",
            "service": "edge61"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      containers:
        - name: edge61
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/edge61/edge61-service", "--live"]
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
            - name: SENTRY_DSN
              value: "https://45e180eb17ab46aeb9a9bc5b20c9759f@o369902.ingest.sentry.io/6229578"
{{- include "binance.vars" . | nindent 12 }}
{{- include "datadog.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
---
