apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge70-signal-to-tas-bridge
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "edge70-signal-to-tas-bridge"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: edge70-signal-to-tas-bridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "edge70-signal-to-tas-bridge"
        app: edge70-signal-to-tas-bridge
      annotations:
        ad.datadoghq.com/tags: '{"service": "edge70-signal-to-tas-bridge"}'
        ad.datadoghq.com/edge70-signal-to-tas-bridge.logs: >-
          [{
            "source": "nodejs",
            "service": "edge70-signal-to-tas-bridge"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: edge70-signal-to-tas-bridge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/edge70-signal-to-tas-bridge/edge-signal-to-tas-bridge"]
          resources:
            requests:
              memory: 100M
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            failureThreshold: 2 # Set as two to avoid SendMessage lazy connect killing services
            httpGet:
              path: /health
              port: http
          startupProbe: # First time this goes healthy livenessProbe is activated
            httpGet:
              path: /health
              port: http
            failureThreshold: 30 # 30 * 10 = 5 minutes
            periodSeconds: 10
          env:
            - name: SENTRY_DSN
              value: "https://d58e2a72040a48689a2e1933aa2e45da@o369902.ingest.sentry.io/6171400"
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "binance-spot-tas.vars" . | nindent 12 }}
{{- include "binance-futures-tas.vars" . | nindent 12 }}
