apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-to-influxdb
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "portfolio-to-influxdb"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "portfolio-to-influxdb"
      annotations:
        ad.datadoghq.com/tags: '{"service": "portfolio-to-influxdb"}'
        ad.datadoghq.com/portfolio-to-influxdb.logs: >-
          [{
            "source": "nodejs",
            "service": "portfolio-to-influxdb"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: portfolio-to-influxdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/services/portfolio-to-influxdb/portfolio-to-influxdb-service"]
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          env:
            - name: SENTRY_DSN
              value: "https://eef07174512a4c75a326ed7e28165240@o369902.ingest.sentry.io/6111716"
{{- include "telegram.vars" . | nindent 12 }}
{{- include "amqp.vars" . | nindent 12 }}
{{- include "influxdb.vars" . | nindent 12 }}
