apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-performance
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "position-performance"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "position-performance"
        tags.datadoghq.com/service: "position-performance"
      annotations:
        ad.datadoghq.com/tags: '{"service": "position-performance"}'
        ad.datadoghq.com/position-performance.logs: >-
          [{
            "source": "nodejs",
            "service": "position-performance"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: position-performance
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/position-performance/position-performance-service", "--live"]
          # ports:
          # - name: http
          #   containerPort: 80
          #   protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
            - name: SENTRY_DSN
              value: "https://783401c8afe74f84a28d8482f756e380@o369902.ingest.sentry.io/6112675"
{{- include "datadog.vars" . | nindent 12 }}
{{- include "telegram.vars" . | nindent 12 }}
{{- include "redis.vars" . | nindent 12 }}
{{- include "binance-spot-tas.vars" . | nindent 12 }}
