apiVersion: v1
kind: Service
metadata:
  name: telegram-bot-bert
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: telegram-bot-bert
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-bert
  labels:
{{ include "mychart.labels" . | indent 4 }}
    binance-tool/service: "telegram-bot-bert"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: telegram-bot-bert
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        binance-tool/service: "telegram-bot-bert"
        app: telegram-bot-bert
      annotations:
        ad.datadoghq.com/tags: '{"service": "telegram-bot-bert"}'
        ad.datadoghq.com/telegram-bot-bert.logs: >-
          [{
            "source": "nodejs",
            "service": "telegram-bot-bert"
          }]   
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: telegram-bot-bert
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "./out/./services/telegram-bot-bert/bert"]
          ports:
          - name: http
            containerPort: 3000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          env:
            - name: SENTRY_DSN
              value: "https://d9432d76fae6438b87ca9bf63e5b098d@o369902.ingest.sentry.io/6152177"
            - name: TRADE_ABSTRACTION_SERVICE_URL
              value: "http://spot-trade-abstraction"
            - name: DEBUG
              value: "telegraf:*"
{{- include "telegram-bot-bert.vars" . | nindent 12 }}
