apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telegram-bot-bert-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "bert.ryancocks.net"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: telegram-bot-bert
            port:
              number: 3000
