# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


#
# The default values yaml may be being used for production so beware
# 
replicaCount: 1

image:
  repository: "ghcr.io/subos2008/binance-tool/binance-tool"
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Used by the post deploy test
service:
  type: ClusterIP
  port: 80

redis:
  database_number: "0" # production - not overriden during deploy so do not change
