name: Check Cluster (Staging Terraform)

on:
  push:
    branches:
      - master
    # paths:
    #   - terraform/clusters

# c.f. https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  # cancel-in-progress: true # too dangerous, can leave half installed charts that need manual intervention to rollback

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TF_STATE_BUCKET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_STATE_BUCKET_SECRET }}
  TF_VAR_DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  TF_VAR_DIGITALOCEAN_CLUSTER_NAME: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

jobs:
  do-cluster:
    runs-on: ubuntu-latest
    environment: te-staging

    defaults:
      run:
        shell: bash
        working-directory: terraform/clusters/staging/0100-do-cluster

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - uses: autero1/action-terragrunt@v1.1.1
        with:
          terragrunt_version: 0.38.12 # latest at the time of writing

      - name: Terragrunt Plan
        run: terragrunt plan
