name: TypeScript Compile
on:
  push:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Yarn install
        run: yarn install
      - name: Compile
        run: ./node_modules/.bin/tsc
